<a href="https://colab.research.google.com/github/PreethiPara/Churn-Modelling-ANN-/blob/main/Churn_prediction_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf


In [ ]:
tf.__version__

'2.9.2'

In [ ]:
df=pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
df.shape

(10000, 14)

In [ ]:
x=df.drop(['Exited','RowNumber','CustomerId','Surname'],axis=1)
y=df.Exited
print(x)
print(y)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0           

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
map1={'Female':1,'Male':0}
x.Gender=x['Gender'].map(map1)
x.head()



CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       1   42       2       0.00              1   
1          608     Spain       1   41       1   83807.86              1   
2          502    France       1   42       8  159660.80              3   
3          699    France       1   39       1       0.00              2   
4          850     Spain       1   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [ ]:
print(x)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       1   42       2       0.00              1   
1             608     Spain       1   41       1   83807.86              1   
2             502    France       1   42       8  159660.80              3   
3             699    France       1   39       1       0.00              2   
4             850     Spain       1   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       0   39       5       0.00              2   
9996          516    France       0   35      10   57369.61              1   
9997          709    France       1   36       7       0.00              1   
9998          772   Germany       0   42       3   75075.31              2   
9999          792    France       1   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0           

In [ ]:
#Dummies on the 'Geography' column

temp=pd.get_dummies(df.Geography)
temp.head()
x.drop('Geography',axis=1,inplace=True)
x=pd.concat([x,temp],axis=1)
x.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       1   42       2       0.00              1          1   
1          608       1   41       1   83807.86              1          0   
2          502       1   42       8  159660.80              3          1   
3          699       1   39       1       0.00              2          0   
4          850       1   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  France  Germany  Spain  
0               1        101348.88       1        0      0  
1               1        112542.58       0        0      1  
2               0        113931.57       1        0      0  
3               0         93826.63       1        0      0  
4               1         79084.10       0        0      1

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x)
p=scaler.transform(x)
print(x)
print(p)

      CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       1   42       2       0.00              1          1   
1             608       1   41       1   83807.86              1          0   
2             502       1   42       8  159660.80              3          1   
3             699       1   39       1       0.00              2          0   
4             850       1   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       0   39       5       0.00              2          1   
9996          516       0   35      10   57369.61              1          1   
9997          709       1   36       7       0.00              1          0   
9998          772       0   42       3   75075.31              2          1   
9999          792       1   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  France  Germ

In [ ]:

scaler.fit(x_train)
x_train=scaler.transform(x_train)

scaler.fit(x_test)
x_test=scaler.transform(x_test)

In [ ]:
print(x_train)

[[0.634      1.         0.22857143 ... 0.         0.         1.        ]
 [0.154      0.         0.34285714 ... 0.         1.         0.        ]
 [0.37       1.         0.15714286 ... 1.         0.         0.        ]
 ...
 [0.776      0.         0.24285714 ... 1.         0.         0.        ]
 [0.48       1.         0.28571429 ... 0.         0.         1.        ]
 [0.546      1.         0.42857143 ... 0.         1.         0.        ]]


**BUILDING ANN**

In [ ]:
print(x_test)

[[0.47835052 1.         0.22972973 ... 0.         1.         0.        ]
 [0.3257732  1.         0.2972973  ... 1.         0.         0.        ]
 [0.70309278 1.         0.32432432 ... 0.         0.         1.        ]
 ...
 [0.43917526 0.         0.24324324 ... 0.         0.         1.        ]
 [0.58762887 0.         0.21621622 ... 0.         1.         0.        ]
 [0.42886598 0.         0.16216216 ... 0.         1.         0.        ]]


Initializing and Building the ANN

In [ ]:
ann=tf.keras.models.Sequential()


Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))


Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))


Adding output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

Compiling the ANN


In [ ]:
ann.compile(optimizer='adam' , loss='binary_crossentropy' , metrics=['accuracy'])


Training ANN on training set

In [ ]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)


Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6676 - accuracy: 0.5695
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4879 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4689 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4600 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4531 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4475 - accuracy: 0.7987
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4436 - accuracy: 0.8030
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4400 - accuracy: 0.8059
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4366 - accuracy: 0.8058
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4345 - accura

In [ ]:
ann.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (32, 6)                   78        
                                                                 
 dense_4 (Dense)             (32, 6)                   42        
                                                                 
 dense_5 (Dense)             (32, 1)                   7         
                                                                 
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________


France=[1,0,0],spain=[0,0,1],germany=[0,1,0]

Making predictions and evaluating the model

In [ ]:
print(ann.predict(scaler.transform([[600, 1, 40, 3, 60000, 2, 1, 1, 50000,1,0,0],[619	,1,42,	2,	0.00,	1,	1,	1,	101348.88,1,0,0		]])))


1/1 [==============================] - 0s 91ms/step
[[0.13296603]
 [0.38163882]]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [ ]:
y_pred=ann.predict(x_test)
 
print(np.asarray(y_test))
print(y_pred)

63/63 [==============================] - 0s 1ms/step
[0 1 0 ... 0 0 0]
[[0.17283091]
 [0.21080953]
 [0.15517427]
 ...
 [0.30412683]
 [0.12799765]
 [0.10923845]]


In [ ]:
from sklearn.metrics import accuracy_score
y_pred=(y_pred>0.5)

acc=accuracy_score(y_test,y_pred)
print(acc)

0.842


In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
y_test=np.asarray(y_test) #.reshape(1,-1).reshape(len(y_test),1)
print(y_pred)

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]
              precision    recall  f1-score   support

           0       0.85      0.98      0.91      1595
           1       0.78      0.31      0.44       405

    accuracy                           0.84      2000
   macro avg       0.81      0.64      0.67      2000
weighted avg       0.83      0.84      0.81      2000

[[1560   35]
 [ 281  124]]


In [ ]:
y_pred=ann.predict(x_test)
y_test_class=np.argmax(y_test,axis=1)
y_pred_class=np.argmax(y_pred,axis=1)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(accuracy_score(y_test_class,y_pred_class))
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

63/63 [==============================] - 0s 1ms/step
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2000

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

[[2000]]


In [ ]:
param_grid=dict(neurons=neurons,batch_size=batch_size,epochs=epochs,activation=activation,optimizer=optimizer,loss=loss)
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=ann,param_grid=param_grid,n_jobs=-1)
grid_result=grid.fit(x_train,y_train)
print(grid_result.best_score_)
print(grid_result.best_params_)


def ann_model(neurons,activation,optimizer,loss):

   ann=tf.keras.models.Sequential()
   ann.add(tf.keras.layers.Dense(units=neurons,activation=activation))
   ann.add(tf.keras.layers.Dense(units=neurons,activation=activation))
   ann.add(tf.keras.layers.Dense(units=2,activation='softmax'))
   ann.compile(optimizer=optimizer,loss=loss,metrics=['accuracy'])
   return ann

#Defining hyperparameters to find best fit

from keras.wrappers.scikit_learn import KerasClassifier
ann=KerasClassifier(build_fn=ann_model,verbose=0)
neurons=[16]
batch_size=[32]
epochs=[100]
activation=['relu']
optimizer=['SGD']
loss=['squared_hinge']




NameError: ignored